services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - ./core/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "./celery_manager/entry_point.sh"]
    depends_on:
      - redis


volumes:
  postgres_data:
  redisdata: