services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    #   - redis

  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: test_db1
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5433:5432"

  # redis:
  #   image: redis:7

  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A celery_app worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - db

volumes:
  postgres_data: